"""empty message

Revision ID: 24be8b085c13
Revises: 93a0f13e0839
Create Date: 2023-05-23 06:04:43.913082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24be8b085c13'
down_revision = '93a0f13e0839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
